version: '3'

services:
  db:
    image: postgres
  web:
    build: . 
    command: uwsgi --ini uwsgi.ini         

    volumes:
      - ./yet-another-timelogger:/code
    ports:
      - "8088:8088"
    depends_on:
      - db